spring:
  application:
    name: yourshop
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/yourshop?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc.lob.non_contextual_creation: true
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
  elasticsearch:
    uris: ${SPRING_ELASTICSEARCH_URIS:http://localhost:9200}

server:
  port: 8080

logging:
  level:
    org.springframework.security: INFO
    org.hibernate.SQL: INFO

security:
  jwt:
    secret: ${JWT_SECRET:please-change-this-super-long-secret}
    expirationMs: ${JWT_EXPIRATION_MS:86400000}